name: Deploy to Azure
on:
  push:
    branches:
      - '**'

jobs:

  deploy:
    name: Deployment
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        run: |
          az containerapp up -n node-calculator --ingress external --source .

